server:
  ssl:
    key-store-password: changeit
    key-store-type: PKCS12
    enabled: true
    key-store: classpath:java_ssl.p12

bot:
  name: "t.me/managment_webapp_bot"
  token: "5839777758:AAE5RcdjHyLPcJ3QjvKRaKED8rv9tcI5X64"
  url: "https://192.168.111.159:3000"